parameters:
- name: serviceConnectionName
  type: string
- name: infraProvider
  type: string
  default: 'bicep'
  values:
  - bicep
  - tf

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  displayName: Build Bicep and Function App
  variables:
    armParametersScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts/Add-ArmParametersFromBicepparamFiles.ps1
    mainBicepPath: $(System.DefaultWorkingDirectory)/.infrastructure/bicep/main.bicep
  steps:
    - task: Bash@3
      displayName: Build Infrastructure Templates
      inputs:
        targetType: 'inline'
        script: |
          bicep build $(mainBicepPath)

    - task: PowerShell@2
      displayName: Generate ARM parameters from *.bicepparam
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/.infrastructure/${{ parameters.infraProvider }}/parameters/
        filePath: $(armParametersScriptPath)

    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
      inputs:
        categories: 'IaC'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Infrastructure Artifacts
      inputs:
        artifactName: infrastructure
        targetPath: $(System.DefaultWorkingDirectory)/.infrastructure/
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Scripts
      inputs:
        artifactName: scripts
        targetPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts/