parameters:
- name: serviceConnectionName
  type: string
- name: infraProvider
  type: string
  values:
  - bicep
  - tf
- name: runDefenderForDevOpsScan
  type: boolean
  default: true
- name: logicAppRootFolder
  type: string

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  displayName: Build Bicep and Function App
  variables:
    armParametersScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts/Add-ArmParametersFromBicepparamFiles.ps1
    mainBicepPath: $(System.DefaultWorkingDirectory)/.infrastructure/bicep/main.bicep
  steps:
    - task: Bash@3
      displayName: Build Infrastructure Templates
      inputs:
        targetType: 'inline'
        script: |
          bicep build $(mainBicepPath)

    - task: PowerShell@2
      displayName: Generate ARM parameters from *.bicepparam
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/.infrastructure/${{ parameters.infraProvider }}/parameters/
        filePath: $(armParametersScriptPath)

    - task: ArchiveFiles@2
      displayName: Package Logic App Workflows
      inputs:
        rootFolderOrFile: ${{ parameters.logicAppRootFolder }}
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/logicapp.zip
        replaceExistingArchive: true

    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
      condition: eq(variables.runDefenderForDevOpsScan, true)
      inputs:
        categories: 'IaC'
    
    - publish: $(System.DefaultWorkingDirectory)/.infrastructure/
      displayName: Publish Infrastructure Artifacts
      artifact: infrastructure

    - publish: $$(System.DefaultWorkingDirectory)/.pipelines/scripts/
      displayName: Publish Pipeline Scripts
      artifact: scripts
    
    - publish: $(Build.ArtifactStagingDirectory)/logicapp.zip
      displayName: Publish Logic App Workflows
      artifact: logicapp