parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: deploymentRegion
  type: string
  default: 'eastus'
- name: infraProvider
  type: string
  default: 'bicep'
  values:
    - bicep
    - tf
- name: stageDependencies
  type: object
  default: []

stages:
  - stage: Deploy_to_${{ parameters.environmentName }}
    displayName: Deploy to ${{ parameters.environmentName }}
    dependsOn: ${{ parameters.stageDependencies }}
    jobs:
    - deployment: ${{ parameters.environmentName }}_Deployment
      displayName: ${{ parameters.environmentName }} Deployment
      pool:
        vmImage: ubuntu-latest
      environment: ${{ parameters.environmentName }}
      variables:
        infraTemplate: $(Pipeline.Workspace)/infrastructure/main.bicep
        parameterFile: $(Pipeline.Workspace)/infrastructure/parameters/main.${{ parameters.environmentName }}.json
        variableScriptFile: $(Pipeline.Workspace)/scripts/Set-PipelineVariablesFromDeploymentOutput.ps1
        functionPackage: $(Pipeline.Workspace)/functionapp/functionapp.zip
        setFunctionSecretScriptFile: $(Pipeline.Workspace)/scripts/set-function-key-secret.sh
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: infrastructure
              displayName: Download infrastructure artifact
            
            - download: current
              artifact: scripts
              displayName: Download scripts artifact
            
            - download: current
              artifact: logicapp
              displayName: Download Logic App workflows artifact

            
