parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: deploymentRegion
  type: string
  default: 'eastus'
- name: infraProvider
  type: string
  default: 'bicep'
  values:
    - bicep
    - tf
- name: stageDependencies
  type: object
  default: []

stages:
  - stage: Deploy_to_${{ parameters.environmentName }}
    displayName: Deploy to ${{ parameters.environmentName }}
    dependsOn: ${{ parameters.stageDependencies }}
    jobs:
    - deployment: ${{ parameters.environmentName }}_Deployment
      displayName: ${{ parameters.environmentName }} Deployment
      pool:
        vmImage: ubuntu-latest
      environment: ${{ parameters.environmentName }}
      variables:
        infraTemplate: $(Pipeline.Workspace)/infrastructure/${{ parameters.infraProvider }}/main.${{ parameters.infraProvider }}
        parameterFile: $(Pipeline.Workspace)/infrastructure/parameters/main.${{ parameters.environmentName }}.json # Will need to look at making this work with TF later
        lociAppPackage: $(Pipeline.Workspace)/logicapp/logicapp.zip
        setFunctionSecretScriptFile: $(Pipeline.Workspace)/scripts/set-function-key-secret.sh
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: infrastructure
              displayName: Download infrastructure artifact
            
            - download: current
              artifact: scripts
              displayName: Download scripts artifact
            
            - download: current
              artifact: logicapp
              displayName: Download Logic App workflows artifact
            
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy infrastructure to ${{ parameters.environmentName}}
              condition: eq('${{ parameters.infraProvider }}', 'bicep')
              inputs:
                deploymentMode: 'Incremental'
                deploymentScope: 'Resource Group'
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.deploymentRegion }}
                azureResourceManagerConnection: ${{ parameters.serviceConnectionName }}
                csmFile: ${{ variables.infraTemplate }}
                csmParametersFile: ${{ variables.parameterFile }}
                overrideParameters: '-buildId $(Build.BuildId)'            
