parameters:


trigger:
  branches:
    include:
     - '*'
pr: none

variables:
 - name: infraProvider
   value: 'tf'
 - name: deployToDev
   value: true
 - name: deployToQa
   value: false
 - name: deployToPrd
   value: false
 - name: runDefenderForDevOpsScan
   value: false
 - name: logicAppRootFolder
   value: $(System.DefaultWorkingDirectory)/src/
 - name: serviceConnectionName
   value: 'Christopher House - Internal Demo Sub'

stages:
 - stage: Build
   displayName: Build Infrastructure and Code
   jobs:
   - template: templates/build.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       infraProvider: ${{ variables.infraProvider }}
       runDefenderForDevOpsScan: ${{ variables.runDefenderForDevOpsScan }}
       logicAppRootFolder: ${{ variables.logicAppRootFolder }}



 - ${{ if eq(variables.deployToDev, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: dev
       resourceGroupName: LA-CI-CD-DEV
       stageDependencies: [Build]
       infraProvider: ${{ variables.infraProvider }}
       tfStateStorageAccountName: "cmhtfstate"
       tfStateStorageAccountResourceGroupName: TF
       subscriptionId: 'e1f57a36-4892-4716-9a3f-661432b39dbe'
       terraformKeyVaultName: 'tf-deploy-kv'


 - ${{ if eq(variables.deployToQa, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: qa
       resourceGroupName: LA-CI-CD-QA
       stageDependencies: [Deploy_to_dev]
       infraProvider: ${{ variables.infraProvider }}
       tfStateStorageAccountName: ""
       tfStateStorageAccountResourceGroupName: ""
       subscriptionId: '*'
       terraformKeyVaultName: ''

 - ${{ if eq(variables.deployToPrd, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: prd
       resourceGroupName: LA-CI-CD-PRD
       stageDependencies: [Deploy_to_qa]
       infraProvider: ${{ variables.infraProvider }}
       tfStateStorageAccountName: ""
       tfStateStorageAccountResourceGroupName: ""
       subscriptionId: '*'
       terraformKeyVaultName: ''

