parameters:
- name: serviceConnectionName
  displayName: Azure DeveOps Service Connection Name
  type: string
  default: 'Christopher House - Internal Demo Sub'

trigger:
  branches:
    include:
     - '*'
pr: none

variables:
 - name: infraProvider
   value: 'bicep'
 - name: deployToDev
   value: true
 - name: deployToQa
   value: false
 - name: deployToPrd
   value: false
 - name: runDefenderForDevOpsScan
   value: true
 - name: logicAppRootFolder
   value: $(System.DefaultWorkingDirectory)/src/

stages:
 - stage: Build
   displayName: Build Infrastructure and Code
   jobs:
   - template: templates/build.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       infraProvider: ${{ variables.infraProvider }}
       runDefenderForDevOpsScan: ${{ variables.runDefenderForDevOpsScan }}
       logicAppRootFolder: ${{ variables.logicAppRootFolder }}



 - ${{ if eq(variables.deployToDev, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: dev
       resourceGroupName: LA-CI-CD-DEV
       stageDependencies: [Build]


 - ${{ if eq(variables.deployToQa, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: qa
       resourceGroupName: LA-CI-CD-QA
       stageDependencies: [Deploy_to_dev]

 - ${{ if eq(variables.deployToPrd, true) }}:
   - template: templates/deploy.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}
       environmentName: prd
       resourceGroupName: LA-CI-CD-PRD
       stageDependencies: [Deploy_to_qa]
